SET SQL_MODE = "NO_AUTO_VALUE_ON_ZERO";
START TRANSACTION;
SET time_zone = "+00:00";

CREATE TABLE `estudiantes` (
  `id` int(11) NOT NULL,
  `nombre` varchar(255) NOT NULL,
  `apellido` varchar(255) NOT NULL,
  `email` varchar(255) NOT NULL,
  `password` varchar(255) NOT NULL,
  `github` varchar(255) NOT NULL,
  `linkedin` varchar(255) NOT NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

ALTER TABLE `estudiantes`
  ADD PRIMARY KEY (`id`);

ALTER TABLE `estudiantes`
  MODIFY `id` int(11) NOT NULL AUTO_INCREMENT, AUTO_INCREMENT=5;

CREATE TABLE `proyectos` (
  `id` int(11) NOT NULL,
  `titulo` varchar(255) NOT NULL,
  `descripcion` text,
  `fecha_creacion` datetime NOT NULL,
  `creador_id` int(11) DEFAULT NULL,
  `githubproj` varchar(255) NOT NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

ALTER TABLE `proyectos`
  ADD PRIMARY KEY (`id`),
  ADD FOREIGN KEY (`creador_id`) REFERENCES `estudiantes`(`id`);

ALTER TABLE `proyectos`
  MODIFY `id` int(11) NOT NULL AUTO_INCREMENT, AUTO_INCREMENT=667;

CREATE TABLE `estudiantes_proyectos` (
  `estudiante_id` int(11) NOT NULL,
  `proyecto_id` int(11) NOT NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

INSERT INTO `estudiantes` (`id`, `nombre`, `apellido`, `email`, `password`, `github`, `linkedin`) VALUES
(666, 'Raul', 'Moreno', 'raul@gmail.com', 'Aa@123456', 'd0vak1n', 'raulmor');

INSERT INTO `proyectos` (`id`, `titulo`, `descripcion`, `fecha_creacion`, `creador_id`, `githubproj`) VALUES
(111, 'ProjectColabo', 'A wan caballo blanco caballo negroorl ahorarr se calle ustée diodeno apetecan. Torpedo me cago en tus muelas apetecan llevame al sircoo diodenoo llevame al sircoo diodenoo fistro fistro a gramenawer. Mamaar pecador va usté muy cargadoo benemeritaar quietooor diodeno. Está la cosa muy malar pecador ese que llega pupita va usté muy cargadoo está la cosa muy malar ese hombree te voy a borrar el cerito sexuarl mamaar mamaar. Tiene musho peligro a wan por la gloria de mi madre pupita qué dise usteer. Llevame al sircoo pecador al ataquerl mamaar apetecan condemor. Condemor hasta luego Lucas a gramenawer fistro fistro tiene musho peligro te voy a borrar el cerito no puedor fistro sexuarl por la gloria de mi madre. Diodenoo está la cosa muy malar torpedo benemeritaar torpedo. ', '2024-06-17 11:19:13', 666, 'https://github.com/d0vak1n/ProjectColabo'),
(888, 'Twitter', 'Lorem fistrum ahorarr ese que llega fistro no puedor te va a hasé pupitaa. Me cago en tus muelas al ataquerl benemeritaar va usté muy cargadoo diodenoo condemor ese que llega. Mamaar apetecan tiene musho peligro sexuarl diodenoo ese pedazo de. Papaar papaar qué dise usteer benemeritaar mamaar te voy a borrar el cerito. Ese pedazo de amatomaa me cago en tus muelas diodeno condemor. Benemeritaar no puedor papaar papaar por la gloria de mi madre diodenoo de la pradera qué dise usteer no te digo trigo por no llamarte Rodrigor diodenoo ese que llega me cago en tus muelas. Hasta luego Lucas caballo blanco caballo negroorl papaar papaar mamaar diodeno va usté muy cargadoo papaar papaar me cago en tus muelas está la cosa muy malar tiene musho peligro.\r\n\r\nA wan caballo blanco caballo negroorl ahorarr se calle ustée diodeno apetecan. Torpedo me cago en tus muelas apetecan llevame al sircoo diodenoo llevame al sircoo diodenoo fistro fistro a gramenawer. Mamaar pecador va usté muy cargadoo benemeritaar quietooor diodeno. Está la cosa muy malar pecador ese que llega pupita va usté muy cargadoo está la cosa muy malar ese hombree te voy a borrar el cerito sexuarl mamaar mamaar. Tiene musho peligro a wan por la gloria de mi madre pupita qué dise usteer. Llevame al sircoo pecador al ataquerl mamaar apetecan condemor. Condemor hasta luego Lucas a gramenawer fistro fistro tiene musho peligro te voy a borrar el cerito no puedor fistro sexuarl por la gloria de mi madre. Diodenoo está la cosa muy malar torpedo benemeritaar torpedo.\r\n\r\nTiene musho peligro la caidita a peich ese que llega tiene musho peligro quietooor ese que llega. Benemeritaar apetecan pupita sexuarl quietooor tiene musho peligro fistro a wan. No puedor a gramenawer diodenoo quietooor al ataquerl papaar papaar diodenoo ese que llega. De la pradera va usté muy cargadoo te va a hasé pupitaa torpedo está la cosa muy malar mamaar. Ese hombree a gramenawer a wan benemeritaar amatomaa fistro. ', '2024-06-11 20:59:59', 666, 'https://github.com/d0vak1n/ProjectColabo'),
(889, 'Twitter', 'Lorem fistrum ahorarr ese que llega fistro no puedor te va a hasé pupitaa. Me cago en tus muelas al ataquerl benemeritaar va usté muy cargadoo diodenoo condemor ese que llega. Mamaar apetecan tiene musho peligro sexuarl diodenoo ese pedazo de. Papaar papaar qué dise usteer benemeritaar mamaar te voy a borrar el cerito. Ese pedazo de amatomaa me cago en tus muelas diodeno condemor. Benemeritaar no puedor papaar papaar por la gloria de mi madre diodenoo de la pradera qué dise usteer no te digo trigo por no llamarte Rodrigor diodenoo ese que llega me cago en tus muelas. Hasta luego Lucas caballo blanco caballo negroorl papaar papaar mamaar diodeno va usté muy cargadoo papaar papaar me cago en tus muelas está la cosa muy malar tiene musho peligro.\r\n\r\nA wan caballo blanco caballo negroorl ahorarr se calle ustée diodeno apetecan. Torpedo me cago en tus muelas apetecan llevame al sircoo diodenoo llevame al sircoo diodenoo fistro fistro a gramenawer. Mamaar pecador va usté muy cargadoo benemeritaar quietooor diodeno. Está la cosa muy malar pecador ese que llega pupita va usté muy cargadoo está la cosa muy malar ese hombree te voy a borrar el cerito sexuarl mamaar mamaar. Tiene musho peligro a wan por la gloria de mi madre pupita qué dise usteer. Llevame al sircoo pecador al ataquerl mamaar apetecan condemor. Condemor hasta luego Lucas a gramenawer fistro fistro tiene musho peligro te voy a borrar el cerito no puedor fistro sexuarl por la gloria de mi madre. Diodenoo está la cosa muy malar torpedo benemeritaar torpedo.\r\n\r\nTiene musho peligro la caidita a peich ese que llega tiene musho peligro quietooor ese que llega. Benemeritaar apetecan pupita sexuarl quietooor tiene musho peligro fistro a wan. No puedor a gramenawer diodenoo quietooor al ataquerl papaar papaar diodenoo ese que llega. De la pradera va usté muy cargadoo te va a hasé pupitaa torpedo está la cosa muy malar mamaar. Ese hombree a gramenawer a wan benemeritaar amatomaa fistro. ', '2024-06-11 20:59:59', 666, 'https://github.com/d0vak1n/ProjectColabo'),
(890, 'ProjectColabo', 'A wan caballo blanco caballo negroorl ahorarr se calle ustée diodeno apetecan. Torpedo me cago en tus muelas apetecan llevame al sircoo diodenoo llevame al sircoo diodenoo fistro fistro a gramenawer. Mamaar pecador va usté muy cargadoo benemeritaar quietooor diodeno. Está la cosa muy malar pecador ese que llega pupita va usté muy cargadoo está la cosa muy malar ese hombree te voy a borrar el cerito sexuarl mamaar mamaar. Tiene musho peligro a wan por la gloria de mi madre pupita qué dise usteer. Llevame al sircoo pecador al ataquerl mamaar apetecan condemor. Condemor hasta luego Lucas a gramenawer fistro fistro tiene musho peligro te voy a borrar el cerito no puedor fistro sexuarl por la gloria de mi madre. Diodenoo está la cosa muy malar torpedo benemeritaar torpedo. ', '2024-06-17 11:19:13', 666, 'https://github.com/d0vak1n/ProjectColabo'),
(891, 'ProjectColabo', 'A wan caballo blanco caballo negroorl ahorarr se calle ustée diodeno apetecan. Torpedo me cago en tus muelas apetecan llevame al sircoo diodenoo llevame al sircoo diodenoo fistro fistro a gramenawer. Mamaar pecador va usté muy cargadoo benemeritaar quietooor diodeno. Está la cosa muy malar pecador ese que llega pupita va usté muy cargadoo está la cosa muy malar ese hombree te voy a borrar el cerito sexuarl mamaar mamaar. Tiene musho peligro a wan por la gloria de mi madre pupita qué dise usteer. Llevame al sircoo pecador al ataquerl mamaar apetecan condemor. Condemor hasta luego Lucas a gramenawer fistro fistro tiene musho peligro te voy a borrar el cerito no puedor fistro sexuarl por la gloria de mi madre. Diodenoo está la cosa muy malar torpedo benemeritaar torpedo. ', '2024-06-17 11:19:13', 666, 'https://github.com/d0vak1n/ProjectColabo'),
(892, 'ProjectColabo', 'A wan caballo blanco caballo negroorl ahorarr se calle ustée diodeno apetecan. Torpedo me cago en tus muelas apetecan llevame al sircoo diodenoo llevame al sircoo diodenoo fistro fistro a gramenawer. Mamaar pecador va usté muy cargadoo benemeritaar quietooor diodeno. Está la cosa muy malar pecador ese que llega pupita va usté muy cargadoo está la cosa muy malar ese hombree te voy a borrar el cerito sexuarl mamaar mamaar. Tiene musho peligro a wan por la gloria de mi madre pupita qué dise usteer. Llevame al sircoo pecador al ataquerl mamaar apetecan condemor. Condemor hasta luego Lucas a gramenawer fistro fistro tiene musho peligro te voy a borrar el cerito no puedor fistro sexuarl por la gloria de mi madre. Diodenoo está la cosa muy malar torpedo benemeritaar torpedo. ', '2024-06-17 11:19:13', 666, 'https://github.com/d0vak1n/ProjectColabo'),
(893, 'ProjectColabo', 'A wan caballo blanco caballo negroorl ahorarr se calle ustée diodeno apetecan. Torpedo me cago en tus muelas apetecan llevame al sircoo diodenoo llevame al sircoo diodenoo fistro fistro a gramenawer. Mamaar pecador va usté muy cargadoo benemeritaar quietooor diodeno. Está la cosa muy malar pecador ese que llega pupita va usté muy cargadoo está la cosa muy malar ese hombree te voy a borrar el cerito sexuarl mamaar mamaar. Tiene musho peligro a wan por la gloria de mi madre pupita qué dise usteer. Llevame al sircoo pecador al ataquerl mamaar apetecan condemor. Condemor hasta luego Lucas a gramenawer fistro fistro tiene musho peligro te voy a borrar el cerito no puedor fistro sexuarl por la gloria de mi madre. Diodenoo está la cosa muy malar torpedo benemeritaar torpedo. ', '2024-06-17 11:19:13', 666, 'https://github.com/d0vak1n/ProjectColabo'),
(894, 'Twitter', 'Lorem fistrum ahorarr ese que llega fistro no puedor te va a hasé pupitaa. Me cago en tus muelas al ataquerl benemeritaar va usté muy cargadoo diodenoo condemor ese que llega. Mamaar apetecan tiene musho peligro sexuarl diodenoo ese pedazo de. Papaar papaar qué dise usteer benemeritaar mamaar te voy a borrar el cerito. Ese pedazo de amatomaa me cago en tus muelas diodeno condemor. Benemeritaar no puedor papaar papaar por la gloria de mi madre diodenoo de la pradera qué dise usteer no te digo trigo por no llamarte Rodrigor diodenoo ese que llega me cago en tus muelas. Hasta luego Lucas caballo blanco caballo negroorl papaar papaar mamaar diodeno va usté muy cargadoo papaar papaar me cago en tus muelas está la cosa muy malar tiene musho peligro.\r\n\r\nA wan caballo blanco caballo negroorl ahorarr se calle ustée diodeno apetecan. Torpedo me cago en tus muelas apetecan llevame al sircoo diodenoo llevame al sircoo diodenoo fistro fistro a gramenawer. Mamaar pecador va usté muy cargadoo benemeritaar quietooor diodeno. Está la cosa muy malar pecador ese que llega pupita va usté muy cargadoo está la cosa muy malar ese hombree te voy a borrar el cerito sexuarl mamaar mamaar. Tiene musho peligro a wan por la gloria de mi madre pupita qué dise usteer. Llevame al sircoo pecador al ataquerl mamaar apetecan condemor. Condemor hasta luego Lucas a gramenawer fistro fistro tiene musho peligro te voy a borrar el cerito no puedor fistro sexuarl por la gloria de mi madre. Diodenoo está la cosa muy malar torpedo benemeritaar torpedo.\r\n\r\nTiene musho peligro la caidita a peich ese que llega tiene musho peligro quietooor ese que llega. Benemeritaar apetecan pupita sexuarl quietooor tiene musho peligro fistro a wan. No puedor a gramenawer diodenoo quietooor al ataquerl papaar papaar diodenoo ese que llega. De la pradera va usté muy cargadoo te va a hasé pupitaa torpedo está la cosa muy malar mamaar. Ese hombree a gramenawer a wan benemeritaar amatomaa fistro. ', '2024-06-11 20:59:59', 666, 'https://github.com/d0vak1n/ProjectColabo'),
(895, 'Twitter', 'Lorem fistrum ahorarr ese que llega fistro no puedor te va a hasé pupitaa. Me cago en tus muelas al ataquerl benemeritaar va usté muy cargadoo diodenoo condemor ese que llega. Mamaar apetecan tiene musho peligro sexuarl diodenoo ese pedazo de. Papaar papaar qué dise usteer benemeritaar mamaar te voy a borrar el cerito. Ese pedazo de amatomaa me cago en tus muelas diodeno condemor. Benemeritaar no puedor papaar papaar por la gloria de mi madre diodenoo de la pradera qué dise usteer no te digo trigo por no llamarte Rodrigor diodenoo ese que llega me cago en tus muelas. Hasta luego Lucas caballo blanco caballo negroorl papaar papaar mamaar diodeno va usté muy cargadoo papaar papaar me cago en tus muelas está la cosa muy malar tiene musho peligro.\r\n\r\nA wan caballo blanco caballo negroorl ahorarr se calle ustée diodeno apetecan. Torpedo me cago en tus muelas apetecan llevame al sircoo diodenoo llevame al sircoo diodenoo fistro fistro a gramenawer. Mamaar pecador va usté muy cargadoo benemeritaar quietooor diodeno. Está la cosa muy malar pecador ese que llega pupita va usté muy cargadoo está la cosa muy malar ese hombree te voy a borrar el cerito sexuarl mamaar mamaar. Tiene musho peligro a wan por la gloria de mi madre pupita qué dise usteer. Llevame al sircoo pecador al ataquerl mamaar apetecan condemor. Condemor hasta luego Lucas a gramenawer fistro fistro tiene musho peligro te voy a borrar el cerito no puedor fistro sexuarl por la gloria de mi madre. Diodenoo está la cosa muy malar torpedo benemeritaar torpedo.\r\n\r\nTiene musho peligro la caidita a peich ese que llega tiene musho peligro quietooor ese que llega. Benemeritaar apetecan pupita sexuarl quietooor tiene musho peligro fistro a wan. No puedor a gramenawer diodenoo quietooor al ataquerl papaar papaar diodenoo ese que llega. De la pradera va usté muy cargadoo te va a hasé pupitaa torpedo está la cosa muy malar mamaar. Ese hombree a gramenawer a wan benemeritaar amatomaa fistro. ', '2024-06-11 20:59:59', 666, 'https://github.com/d0vak1n/ProjectColabo');

ALTER TABLE `estudiantes_proyectos`
  ADD PRIMARY KEY (`estudiante_id`,`proyecto_id`),
  ADD KEY `proyecto_id` (`proyecto_id`),
  ADD CONSTRAINT `estudiantes_proyectos_ibfk_1` FOREIGN KEY (`estudiante_id`) REFERENCES `estudiantes` (`id`),
  ADD CONSTRAINT `estudiantes_proyectos_ibfk_2` FOREIGN KEY (`proyecto_id`) REFERENCES `proyectos` (`id`);

COMMIT;